int factorial(int n);
int _strlen_recursion(char *s);
void _print_rev_recursion(char *s);
void _puts_recursion(char *s);
int _pow_recursion(int x, int y);
int _sqrt_recursion(int n);
int sqrt_recursion_2(int i, int j);
int is_prime_number(int n);
int _prime_number_2(int a, int b);
int _putchar(char c);
int is_pal(char *str, int f, int l;);
int str_len(char *sl);
int is_palindrome(char *s);
int wildcmp(char *s1, char *s2);
